services:

  postgres:
    image: postgres:16
    container_name: mycloud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mycloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mycloudpassword(very_secure)
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks:
      - piward-net

  spring-boot:
    build: .
    container_name: mycloud-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mycloud
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mycloudpassword(very_secure)
      JWT_SECRET: iv1Ik/RLOJeQdikecjsIxX/U49Ly/prmRPB4hsqU8QJXOtrYt5gryjTgbce08DAw
      JWT_EXPIRATION_MS: 28800000
      STORAGE_PATH: /mnt/cloud-storage
      MQTT_BROKER: tcp://mosquitto:1883
    volumes:
      - /mnt/cloud-storage:/mnt/cloud/storage
    ports:
      - "8080:8080"
    networks:
      - piward-net
  
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mycloud-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - piward-net

volumes:
  postgres-data:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:

networks:
  piward-net:
