# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/mycloud
spring.datasource.username=postgres
spring.datasource.password=ce45Z!ko8agh!ceF

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (we'll use this in Step 5)
jwt.secret=iv1Ik/RLOJeQdikecjsIxX/U49Ly/prmRPB4hsqU8QJXOtrYt5gryjTgbce08DAw
jwt.expiration-ms=28800000

# File storage path (local for now, will be the SSD path on the Pi)
storage.path=./uploads

# Max file upload sizes
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB